# Generated by Django 3.2.5 on 2021-07-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcategory',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
    ]
