# Generated by Django 3.2.5 on 2021-07-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image_url',
            field=models.URLField(max_length=3000, null=True),
        ),
    ]
